/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedFormIdIndexRouteImport } from './routes/_authenticated/form/$id/index'
import { Route as AuthenticatedFormIdEditIndexRouteImport } from './routes/_authenticated/form/$id/edit/index'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormIdIndexRoute =
  AuthenticatedFormIdIndexRouteImport.update({
    id: '/form/$id/',
    path: '/form/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormIdEditIndexRoute =
  AuthenticatedFormIdEditIndexRouteImport.update({
    id: '/form/$id/edit/',
    path: '/form/$id/edit/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/form/$id': typeof AuthenticatedFormIdIndexRoute
  '/form/$id/edit': typeof AuthenticatedFormIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/form/$id': typeof AuthenticatedFormIdIndexRoute
  '/form/$id/edit': typeof AuthenticatedFormIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/success': typeof SuccessRoute
  '/todos': typeof TodosRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_authenticated/form/$id/': typeof AuthenticatedFormIdIndexRoute
  '/_authenticated/form/$id/edit/': typeof AuthenticatedFormIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/success'
    | '/todos'
    | '/app'
    | '/dashboard'
    | '/forms'
    | '/api/uploadthing'
    | '/sign-in/$'
    | '/form/$id'
    | '/form/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/success'
    | '/todos'
    | '/app'
    | '/dashboard'
    | '/forms'
    | '/api/uploadthing'
    | '/sign-in/$'
    | '/form/$id'
    | '/form/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/success'
    | '/todos'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/_authenticated/forms'
    | '/api/uploadthing'
    | '/sign-in/$'
    | '/_authenticated/form/$id/'
    | '/_authenticated/form/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SuccessRoute: typeof SuccessRoute
  TodosRoute: typeof TodosRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/form/$id/': {
      id: '/_authenticated/form/$id/'
      path: '/form/$id'
      fullPath: '/form/$id'
      preLoaderRoute: typeof AuthenticatedFormIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/form/$id/edit/': {
      id: '/_authenticated/form/$id/edit/'
      path: '/form/$id/edit'
      fullPath: '/form/$id/edit'
      preLoaderRoute: typeof AuthenticatedFormIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedFormIdIndexRoute: typeof AuthenticatedFormIdIndexRoute
  AuthenticatedFormIdEditIndexRoute: typeof AuthenticatedFormIdEditIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedFormIdIndexRoute: AuthenticatedFormIdIndexRoute,
  AuthenticatedFormIdEditIndexRoute: AuthenticatedFormIdEditIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SuccessRoute: SuccessRoute,
  TodosRoute: TodosRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
